website/routes.py
import os
import re
import jwt
import urllib.parse
from zoneinfo import ZoneInfo
from datetime import datetime, timezone
from functools import wraps
from bs4 import BeautifulSoup
from markupsafe import Markup
from random import choice
from flask import (
    Blueprint,
    Response,
    current_app,
    request,
    render_template,
    redirect,
    flash,
    abort,
    jsonify,
    url_for,
    send_from_directory,
)
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from website import generate_token
from .models import Post, Subscriber, Comment, AllUsers
from . import (
    db,
    email,
    SubscriberForm,
    ForgotPasswordForm,
    ResetPasswordForm,
    PostForm,
    LoginForm,
    CommentForm,
)

routes: Blueprint = Blueprint(
    "routes",
    __name__,
    template_folder="../website/posts/",
    static_folder="../website/post_media/",
)


def role_required(role):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if not current_user.is_authenticated:
                abort(403)
            if hasattr(current_user, "user_role") and current_user.user_role == role:
                return f(*args, **kwargs)
            else:
                abort(403)

        return decorated_function

    return decorator


def verification_required():
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if not current_user.is_authenticated:
                abort(401)
            if (
                current_user.user_role == "admin"
                or hasattr(current_user, "verified")
                and current_user.verified == True
            ):
                return f(*args, **kwargs)
            else:
                abort(401)

        return decorated_function

    return decorator


def format_datetime(value, tz_code, format) -> str:
    if value is None:
        return ""
    tz = ZoneInfo(tz_code)
    value = value.astimezone(tz)
    return value.strftime(format)


# ---------------------------------oooo000oooo--------------------------------------#


@routes.route("/")
def index():
    recent_posts = Post.query.order_by(Post.date_created.desc()).all()
    recent_posts_list = []

    for recent_post in recent_posts[:10]:
        recent_post_file = recent_post.html_file

        with open(
            current_app.root_path + "/posts/" + recent_post_file, "r", encoding="utf-8"
        ) as file:
            html_content = file.read()

        soup = BeautifulSoup(html_content, "html.parser")
        # --------------------------------------------------------------------------#
        title = soup.find(id="post_title").text
        banner = soup.find(id="post_banner").get("src")
        banner = re.search(r"""='(.*?)'\)""", str(banner)).group(1).strip()
        date = format_datetime(recent_post.date_created, "Asia/Kolkata", "%d %b, %Y")
        avg_rating = get_avg_rating(recent_post)["avg_rating"]

        recent_posts_list.append(
            {
                "title": title,
                "banner": banner,
                "url": recent_post.url,
                "date": date,
                "rating": avg_rating,
            }
        )
    return render_template(
        "index.html", user=current_user, recent_posts_list=recent_posts_list
    )


@routes.route("/about")
def about() -> str:
    return render_template("about.html", user=current_user)


@routes.route("/sitemap.xml")
def sitemap() -> Response:
    return send_from_directory("static", "sitemap.xml")


@routes.route("/robots.txt")
def robots() -> Response:
    return send_from_directory("static", "robots.txt")


# ---------------------------------oooo000oooo--------------------------------------#


@routes.route("/subscribe", methods=["GET", "POST"])
def subscribe() -> str | Response:
    username = None
    email_id = None
    password = None
    confirm_password = None
    form = SubscriberForm()
    if form.validate_on_submit():
        username = form.username.data
        form.username.data = ""
        email_id = form.email_id.data
        form.email_id.data = ""
        password = generate_password_hash(str(form.password.data), method="scrypt")
        form.password.data = ""
        form.confirm_password.data = ""

    # ----------------oo0oo---------------#
    stripped_email = str(email_id).lower().replace(".", "")
    if "+" in stripped_email:
        stripped_email = re.sub(r"""\+(.*?)@""", "", stripped_email)
    else:
        stripped_email = stripped_email.replace("@", "")

    if request.method == "POST":
        if Subscriber.query.filter_by(username=username).first():
            flash("Username is already taken, try a different one", category="warning")
        elif Subscriber.query.filter_by(email_id=email_id).first():
            flash(
                "An account with this E-mail address already exists", category="warning"
            )
        # ---------------------------------------------------------------------
        elif "username" in form.errors:
            flash("Do not use special characters", category="error")
        elif stripped_email == "shetty777bloggmailcom":
            flash(
                "No no no! Don't do that, that is my e-mail address", category="warning"
            )
        elif "email_id" in form.errors:
            flash("The E-mail address you provided is not valid", category="error")
        elif "password" in form.errors:
            flash(
                "Looks like the two passwords don't match. Make sure they are the same",
                category="error",
            )
        # ---------------------------------------------------------------------
        elif not form.errors:
            try:
                new_subscriber = Subscriber(
                    username=username,
                    email_id=email_id,
                    password=password,
                    user_role="subscriber",
                )
                db.session.add(new_subscriber)
                db.session.commit()

                email.send(
                    subject="E-mail verification for Shetty777",
                    receivers=email_id,
                    body_params={
                        "token": generate_token.generate_token(email_id, "Fresh", 20)
                    },
                    html_template="email/verify.html",
                )

                return render_template("verify_email.html", user=current_user)
            except Exception as e:
                db.session.rollback()
                flash(f"Something didn't go right {e}", category="error")
                return jsonify({"status": "error", "message": e})

    return render_template(
        "subscribe.html",
        user=current_user,
        username=username,
        email_id=email_id,
        password=password,
        confirm_password=confirm_password,
        form=form,
    )


@routes.route("/send_manual_verification")
@role_required("admin")
def send_manual_verification():
    try:
        email_id = urllib.parse.unquote(request.args.get("email"))
        email.send(
            subject="E-mail verification for Shetty777",
            receivers=email_id,
            body_params={"token": generate_token.generate_token(email_id, "Fresh", 20)},
            html_template="email/verify_refreshed.html",
        )
        flash("Verification E-mail sent to", category="success")
    except Exception as e:
        flash(f"Something didn't go right {e}", category="error")
        return jsonify({"status": "error", "message": e})
    return redirect("/subscriber_list")


@routes.route("/verify_email/<token>")
def verify_email(token):
    try:
        token_data = jwt.decode(
            token,
            current_app.config["SECRET_KEY"],
            algorithms=["HS256"],
            options={"verify_exp": False},
        )
        email_id = token_data["email_id"]
        token_type = token_data["token_type"]
        exp = token_data["exp"]
        new_subscriber = Subscriber.query.filter_by(email_id=email_id).first()
        if int(datetime.now(tz=timezone.utc).timestamp()) < exp:
            try:
                if new_subscriber.verified == False:
                    new_subscriber.verified = True
                    db.session.commit()

                    flash(
                        "Thank you for subscribing. You can now continue to login",
                        category="success",
                    )
                    return redirect("/login")

                elif new_subscriber.verified == True:
                    flash(
                        "Your E-mail address has already been verified",
                        category="success",
                    )
                else:
                    pass
            except Exception as e:
                db.session.rollback()
                flash(f"Something didn't go right {e}", category="error")
                return jsonify({"status": "error", "message": e})

        elif (
            token_type == "Fresh"
            and int(datetime.now(tz=timezone.utc).timestamp()) >= exp
        ):
            if new_subscriber.verified == False:
                email.send(
                    subject="E-mail verification for Shetty777 [Refreshed token]",
                    receivers=new_subscriber.email_id,
                    body_params={
                        "token": generate_token.generate_token(
                            email_id, "Refresh", 4320
                        )
                    },
                    html_template="email/verify_refreshed.html",
                )
                return render_template("verify_email_refreshed.html", user=current_user)
            elif new_subscriber.verified == True:
                flash(

website/templates/about.html
{% extends "base.html" %} {% block title %}About | Shetty777{% endblock %} {%
block description %}About Shetty77. Know about the context, scope and purpose of
this blog site{% endblock %} {% block content %}
<div class="container">
  <div
    class="container"
    style="max-width: 750px; text-align: start; padding: 20px 0"
  >
    <h1 class="display-2">Welcome to my blog!</h1>
    <p style="text-indent: 3rem">
      This website started out as a simple hobby project in 2020 I suppose, but
      it came to a halt very quickly. I did get some things done here-and-there
      during some vacations, but made giant leaps in the project in summer
      vacations of 2024, although it did eat up a lot of time. I just wanted a
      way to share my writings and projects on the internet, and here is the
      result of that. But the best part of this wasn't actually the website
      itself, but the sheer amount of experience I gained in Python & its Flask
      library, CSS & Bootstrap library, a sprinkle of JavaScript, utilising A.I.
      for assistance and just programming in general. I am quite satisfied with
      result, but it is never complete. I <em>might</em> add more features,
      upgrade hosting and other stuff in the future.
    </p>
    <p style="text-indent: 3rem">
      Maintaining consistency here while also trying to perform well
      academically is going to be challenging. I will try my best to keep
      posting content, but we'll see...
    </p>
    <p>
      And I have to express my gratitude to you for even checking out this
      little project by a kid. So,
      <em><strong>Thank you :)</strong></em>
    </p>

    <br /><br />
    <h2 class="display-6">What's new?</h2>
    <p style="text-indent: 3rem">
      <b>30/08/2025</b> - Increased the time duration for verification links. It
      looks like because of some issue, the users were receiving the mails with
      a long delay; even though the mail had been sent from the blog's account.
    </p>
    <p style="text-indent: 3rem">
      <b>28/06/2025</b> - Fixed a security issue. Anyone was able to log in to a
      subscriber's account if they had access to the confirmation email. So, as
      in other websites, you will be redirected to the login page after
      verification instead of being logged in. Please cooperate.
    </p>
    <p style="text-indent: 3rem">
      <b>21/04/2025</b> - The abbr tags in HTMl are not touch-screen friendly. I
      overrode the default behaviour to use tooltips instead; allowing mobile
      users to access them as well.
    </p>
    <p style="text-indent: 3rem">
      <b>20/04/2025</b> - Some refining changes in the backend. The notification
      subject will now be chosen at random from a list of subjects instead of a
      single subject.
    </p>
    <p style="text-indent: 3rem">
      <b>13/04/2025</b> - The favicon has been added. I have added te website to
      Google Search Console and waiting for indexing. There is a sitemap as
      well.
    </p>
    <p style="text-indent: 3rem">
      <b>09/10/2024</b> - REMOVED REDIS CACHING! Gosh. And......I added a
      provision for password reset. Because you guys kept forgetting it
      &#128529;
    </p>
    <p style="text-indent: 3rem">
      <b>06/10/2024</b> - I have implemented basic levels of Redis caching in
      the website to optimise performance. Load times of commonly accessed pages
      should be lesser.
    </p>

    <br /><br />
    <h2 class="display-6">What to expect?</h2>
    <p style="text-indent: 3rem">
      The following are in the back of my mind for maybe upgrading this website
      in the future:
    </p>

    <ul>
      <li>
        <b>Blogs:</b> Not just articles and projects, but periodical content
        about various fields
      </li>
      <li>
        <b>Search tool:</b> Adding a search functionality to the posts when
        there are a lot of them
      </li>
      <li><b>Tags:</b> Adding tags on posts [not likely]</li>
      <li>
        <b>Better hosting:</b> Maybe, upgrade the hosting service and get a new
        address? It is expensive though
      </li>
    </ul>

    <br /><br />
    <h2 class="display-6">Data storage</h2>
    <p style="text-indent: 3rem">
      I mean, this is not the most secure or robust website! But be rest assured
      that all of your passwords (the only "sensitive" data in this whole
      website) are stored <em>securely after hashing</em> and in no step is it
      handled in plain text. Just make sure to not share any sensitive
      information anywhere (like in comments).
    </p>
    <p style="text-indent: 3rem">
      Other than that, posts marked by you will only be accessible and visible
      to you, your <strong>username</strong> will be visible to all users, your
      <strong>E-Mail</strong> address will only be accessible by the website
      itself (for sending mails, duh) and visible only to me.
    </p>

    <br /><br />
    <h2 class="display-6">Responsible use and admin authority</h2>
    <p style="text-indent: 3rem">
      I have not pen-tested or secured this website with any world-class
      security, so <em>please</em> don't deliberately try to break it in any
      way. Please be mindful and appropriate while setting your username and
      commenting on posts. Any violation/abuse of website functionality or
      inappropriate content will lead to deletion of the comment or the user
      themselves upon my decision.
    </p>
    <p style="text-indent: 3rem">
      You may request/complain/inform about anything to me by sending an
      <abbr title="shetty777.blog@gmail.com">E-mail</abbr>. You can also request
      for subscriber account deletion by doing the same or clicking the "Request
      deletion" button in your user dashboard.
    </p>
  </div>
</div>
{% endblock %}

website/templates/articles.html
{% extends "base.html" %}

{% block title %}Articles | Shetty777{% endblock %}
{% block description %}Explore wonderful articles, essays, speeches and debates on Shetty777{% endblock %}

{% block content %}
<div class='container'>
	<br>
	<h1 style="font-family:Buttermilk; font-size: 4rem;">Articles</h1>
	<h5>Explore a rich collection of thought-provoking essays, speeches, analyses and debates</h5>
	<br>
	<div class="row">
		{% for article in articles_list %}
		<div class="col-md-4">
			<div class="card pop-up-card" style="margin: 0.5rem; border-radius: 20px;">
				<img src="{{ url_for('.static', filename = article.banner) }}" class="card-img-top"
					alt="{{article.title}}"
					style="object-fit: cover; height:12.5rem; border-radius: 20px 20px 0px 0px;">
				<div class="card-body">
					<h5 class="card-title post-card-title" style="font-family: LibreFranklin; font-weight: bold">{{
						article.title }} </h5>
					<a class="stretched-link" href="{{ url_for('routes.web_posts', post_url=article.url) }}"></a>
					<p class="card-text"><small class="text-body-secondary">Posted on: {{ article.date }}</small></p>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

website/templates/blogs.html
{% extends "base.html" %}

{% block title %}Blogs | Shetty777{% endblock %}

{% block content %}
<div class='container' style="display: block; text-align: center;">
	<br>
	<h1 style="font-family:Buttermilk; font-size: 4rem;">Blogs</h1>
	<img src="{{ url_for('static', filename='images/Construction.webp') }}" alt="Under construction" style="width: 50vw">
	<br>
	<h2>This is new to me. Still working on it. Please wait a few weeks</h2>
</div>
{% endblock %}

website/templates/footer.html
<div class="d-flex flex-column h-100">
    <footer class="w-100 py-4 flex-shrink-0 bg-body-tertiary">
        <div class="container py-4">
            <div class="row gy-4 gx-5">
                <div class="col-md-3">
                    <img src="{{ url_for('static', filename='images/Profile.webp') }}" alt="Shashank Shetty"
                        class="img-fluid"
                        style="background: linear-gradient(white, white) padding-box,
                    linear-gradient(135deg, #9000FF, #D000FF) border-box; border-radius: 50em; border: 3px solid transparent; width: 150px">
                </div>
                <div class="col-md-3" style="word-wrap: break-word;">
                    <h5>About me:</h5>
                    <h6 class="text-body-secondary" style="font-family:Roboto">Shashank S Shetty,</h6>
                    <h6 class="text-body-secondary" style="font-family:Roboto; font-size: small;">A curious student,
                        <br>Self-taught coder
                        <br>and an Amateur scribbler
                    </h6>
                    <h6 class="text-body-secondary" style="font-family:Roboto"><br>shetty777.blog@gmail.com
                        <br>kmkshashank@gmail.com
                    </h6>
                </div>
                <div class="col-md-3">
                    <h5 class="mb-3">Links:</h5>
                    <p class="text-body-secondary">
                        <a href="{{url_for('routes.about')}}" class="text-reset">About</a>
                        <br><a href="{{url_for('routes.articles')}}" class="text-reset">Articles</a>
                        <br><a href="{{url_for('routes.projects')}}" class="text-reset">Projects</a>
                        <br><a href="{{url_for('routes.blogs')}}" class="text-reset">Blogs</a>
                        <br><a href="{{url_for('routes.subscribe')}}" class="text-reset">Subscribe</a>
                        <br><a href="{{url_for('routes.login')}}" class="text-reset">Login</a>
                    </p>
                </div>
                <div class="col-md-3" style="word-wrap: break-word;">
                    <h5 class="mb-3">Attributions:</h5>
                    <p class="text-body-secondary">
                        <a href="https://storyset.com" class="text-reset">Storyset</a>
                        <br><a href="https://www.dfonts.org" class="text-reset">Dfonts</a>
                        <br><a href="https://fonts.google.com" class="text-reset">Google Fonts</a>
                        <br><a href="https://cloud.google.com/text-to-speech" class="text-reset">Google TTS</a>
                        <br><a href="https://blog.medium.com" class="text-reset">Medium (UI inspiration)</a>
                    </p>
                </div>
            </div>
        </div>
    </footer>
</div>

website/templates/forgot_password.html
{% extends "base.html" %}
{% block title %}Forgot password | Shetty777{% endblock %}
{% block content %}
<br><br>
<h1 style="font-family: Buttermilk; font-size: 4rem; text-align: center">Forgot Password</h1>
<form method="POST">
	<div class="container d-flex justify-content-center align-items-center">
		<div class="col-sm-12 p-sm-1 p-md-1 p-lg-5 d-flex justify-content-center align-items-center">
			<div class="card mb-5 w-75 rounded-5 custom-border"
				style="padding-top:1rem; box-shadow: 3px 3px 30px rgba(0, 0, 0, 0.500); margin: auto">
				<div class="row g-0">
					<div class="col-md-5 d-flex justify-content-center align-items-center">
						<img src="{{ url_for('static', filename='images/Forgot-password.webp') }}"
							class="card-img mx-auto img-fluid" alt="Login" style="width:20rem">
					</div>
					<div class="col-md-7">
						{{ form.csrf_token }}
						{{ form.hidden_tag() }}
						<p> </p>
						<div class="ms-5 mb-5 me-5">
							{{ form.username_or_email_id.label(class = "form-label", style="font-size: 1rem;") }}
							<div class="input-group flex-nowrap">
								<span class="input-group-text"><i class="bi bi-person-fill"></i></span>
								{{ form.username_or_email_id(class = "form-control custom-input", placeholder="Enter your username or E-mail address") }}
							</div>
						</div>
						<br>
						<div class="container d-flex justify-content-center align-items-center">
							{{ form.send_reset_mail(class = "btn custom-btn btn-lg ms-5 mb-5 me-5",
							style="color:#ffffff; width: 100%") }}
						</div>
						<a href="{{url_for('routes.login')}}" class="text-reset  d-block"
							style="text-align: center">Remembered it? Go back to login</a>
						<p> </p>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login | Shetty777{% endblock %}
{% block description %}log in to your Shetty777 subscriber account{% endblock %}
{% block content %}
<br><br>
<h1 style="font-family: Buttermilk; font-size: 4rem; text-align: center">Subscriber login</h1>
<form method="POST">
	<div class="container d-flex justify-content-center align-items-center">
		<div class="col-sm-12 p-sm-1 p-md-1 p-lg-5 d-flex justify-content-center align-items-center">
			<div class="card mb-5 w-75 rounded-5 custom-border"
				style="padding-top:1rem; box-shadow: 3px 3px 30px rgba(0, 0, 0, 0.500); margin: auto">
				<div class="row g-0">
					<div class="col-md-5 d-flex justify-content-center align-items-center">
						<img src="{{ url_for('static', filename='images/Login.webp') }}"
							class="card-img mx-auto img-fluid" alt="Login" style="width:20rem">
					</div>
					<div class="col-md-7">
						{{ form.csrf_token }}
						{{ form.hidden_tag() }}
						<p> </p>
						<div class="ms-5 mb-5 me-5">
							{{ form.username_or_email_id.label(class = "form-label", style="font-size: 1rem;") }}
							<div class="input-group flex-nowrap">
								<span class="input-group-text"><i class="bi bi-person-fill"></i></span>
								{{ form.username_or_email_id(class = "form-control custom-input", placeholder="Enter your username or E-mail address") }}
							</div>
						</div>
						<div class="ms-5 mb-5 me-5">
							{{ form.password.label(class = "form-label", style="font-size: 1rem;") }}
							<div class="input-group flex-nowrap">
								<span class="input-group-text"><i class="bi bi-key-fill"></i></span>
								{{ form.password(class = "form-control custom-input", placeholder="Enter a password") }}
							</div>
						</div>
						<br>
						<div class="container d-flex justify-content-center align-items-center">
							{{ form.login(class = "btn custom-btn btn-lg ms-5 mb-5 me-5", style="color:#ffffff; width:
							100%") }}
						</div>
						<a href="{{url_for('routes.subscribe')}}" class="text-reset  d-block"
							style="text-align: center">Not a subscriber? Click here to become one</a>
						<p> </p>
						<a href="{{url_for('routes.forgot_password')}}" class="text-reset  d-block"
							style="text-align: center">Forgot password? Click here to reset</a>
						<p> </p>
					</div>
				</div>
			</div>
		</div>
	</div>
</form>
{% endblock %}

website/templates/navbar.html
<nav class=" autohide navbar navbar-expand-lg bg-body-tertiary fixed-top" style="box-shadow: 2px 2px 30px black">
    <div class="container">
        <a class="navbar-brand" href="{{url_for('routes.index')}}">
            <img src="{{ url_for('static', filename='images/logo_text.webp') }}" alt="Shetty777" width="75" height="75">
        </a>
        <button class="navbar-toggler btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('routes.articles')}}">Articles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('routes.projects')}}">Projects</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('routes.blogs')}}">Blogs</a>
                </li>
                <div class="vertical-separator d-none d-lg-block"></div>
                {% if user.is_authenticated and user.user_role!='admin' %}
                <li class="nav-item">
                    <a class="nav-link"
                        href="{{url_for('routes.dashboard', username= user.username|urlencode)}}">Dashboard</a>
                </li>
                {% elif user.is_authenticated and user.user_role=='admin' %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">Administrator</a>
                    <ul class="dropdown-menu p-1">
                        <li><a class="nav-link"
                                href="{{url_for('routes.dashboard', username= user.username|urlencode)}}"><i
                                    class="bi bi-person-badge"></i>&ensp;Dashboard</a></li>
                        <li><a class="nav-link" href="{{url_for('routes.subscriber_list')}}"><i
                                    class="bi bi-bell"></i>&ensp;Subscribers</a></li>
                        <li><a class="nav-link" href="{{url_for('routes.post_list')}}"><i
                                    class="bi bi-list-ul"></i>&ensp;Post list</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="nav-link" href="{{url_for('routes.post')}}"><i
                                    class="bi bi-send"></i>&ensp;Post</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="nav-link" href="{{url_for('routes.logout')}}"><i
                                    class="bi bi-box-arrow-right"></i>&ensp;Signout</a></li>
                    </ul>
                </li>
                {% else %}
                <li>
                    <a class="nav-link" href="{{url_for('routes.login')}}">Login</a>
                </li>
                {% endif %}
            </ul>

            <hr class="d-lg-none">

            <ul class="navbar-nav ms-auto">
                <li><a class="nav-link" href="{{ url_for('routes.about') }}"><i class="bi bi-patch-question-fill"></i>
                        About</a></li>
                <li><a class="nav-link" href="mailto:shetty777.blog@gmail.com"><i class="bi bi-envelope-fill"></i>
                        Gmail</a></li>
                <li><a class="nav-link" href="https://www.github.com/Shetty-777"><i class="bi bi-github"></i> Github</a>
                </li>
                <li><a class="nav-link" href="https://www.youtube.com/@shetty777-blog"><i class="bi bi-youtube"></i>
                        Youtube</a></li>

                <hr class="d-lg-none">
                <div class="vertical-separator d-none d-lg-block"></div>

                <li class="nav-item align-items-center d-flex">
                    <i class="bi bi-brightness-high-fill"></i>
                    <div class="ms-2 form-check form-switch">
                        <input class="form-check-input" type="checkbox" role="switch" id="themeSwitcher" checked>
                    </div>
                    <i class="bi bi-moon-stars-fill"></i>
                </li>
            </ul>
        </div>
    </div>
</nav>

website/templates/sublist.html
{% extends "base.html" %}
{% block title %}List of subscribers | Shetty777{% endblock %}
{% block content %}
<br><br>
<div class="container d-flex justify-content-center align-items-center table-responsive">
  <table class="table table-bordered table-striped table-responsive"
    style="margin:2rem; position:relative; box-shadow: 3px 3px 30px rgba(0, 0, 0, 0.500);">
    <thead>
      <th scope="col">#</th>
      <th scope="col">Username</th>
      <th scope="col">Email address</th>
      <th scope="col">Verified?</th>
      <th scope="col">Date subscribed</th>
      <th scope="col">Delete</th>
    </thead>
    <tbody class="table-group-divide"></tbody>
    {% for subscriber in sublist%}
    <tr>
      <td>{{ subscriber.id }}</td>
      <td>{{ subscriber.username }}</td>
      <td>{{ subscriber.emailid }}</td>
      {% if subscriber.verified == True %}
      <td>Yes</td>
      {% else %}
      <td><a type="button" class="btn btn-sm btn-outline-primary"
          href="{{ url_for('routes.send_manual_verification', email= subscriber.emailid|urlencode, user= subscriber.username|urlencode) }}">No</a>
      </td>
      {% endif %}
      <td>{{ subscriber.date_subscribed | format_datetime('Asia/Kolkata', '%d/%m/%Y %I:%M %p') }}</td>
      <td><button type="button" class="btn btn-sm btn-outline-danger" data-bs-toggle="modal"
          data-bs-target="#confirmationModal" data-bs-delsubname="{{ subscriber.username }}"
          data-bs-delsubid="{{ subscriber.id }}">Delete</button></td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
<div class="modal fade" id="confirmationModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="confirmationModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Subscriber deletion confirmation</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p id="deletionmodaltext"></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
        <a type="button" class="btn btn-danger delete-subscriber" data-subscriber-id="#">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}